var ctx = document.getElementById("qtde_cidade").getContext('2d');
var qtde_dia = new Chart(ctx, {
    type: 'bar',
    data: {
        labels: ["ADAMANTINA",
            "ADOLFO",
            "AGUAI",
            "AGUAS DE LINDOIA",
            "AGUAS DE SANTA BARBARA",
            "AGUDOS",
            "ALTINOPOLIS",
            "ALTO ALEGRE",
            "ALUMINIO",
            "ALVARES MACHADO",
            "ALVARO DE CARVALHO",
            "AMERICANA",
            "AMERICO BRASILIENSE",
            "AMERICO DE CAMPOS",
            "AMPARO",
            "ANALANDIA",
            "ANDRADINA",
            "ANGATUBA",
            "ANHEMBI",
            "APARECIDA",
            "APIAI",
            "ARACARIGUAMA",
            "ARACATUBA", "ARACOIABA DA SERRA", "ARAMINA", "ARARAQUARA", "ARARAS", "ARCO IRIS", "ARTUR NOGUEIRA", "ARUJA", "ASSIS", "ATIBAIA", "AURIFLAMA", "AVANHANDAVA", "AVARE", "BADY BASSITT", "BARIRI", "BARRA BONITA", "BARRA DO TURVO", "BARRETOS", "BARRINHA", "BARUERI", "BASTOS", "BATATAIS", "BAURU", "BEBEDOURO", "BENTO DE ABREU", "BERNARDINO DE CAMPOS", "BERTIOGA", "BIRIGUI", "BIRITIBA MIRIM", "BOA ESPERANCA DO SUL", "BOFETE", "BOITUVA", "BOM JESUS DOS PERDOES", "BOM SUCESSO DE ITARARE", "BORBOREMA", "BOTUCATU", "BRAGANCA PAULISTA", "BRAUNA", "BRODOWSKI", "BROTAS", "BURI", "BURITAMA", "BURITIZAL", "CABREUVA", "CACAPAVA", "CACHOEIRA PAULISTA", "CACONDE", "CAFELANDIA", "CAIEIRAS", "CAIUA", "CAJAMAR", "CAJATI", "CAJURU", "CAMPINA DO MONTE ALEGRE", "CAMPINAS", "CAMPO LIMPO PAULISTA", "CAMPOS DO JORDAO", "CAMPOS NOVOS PAULISTA", "CANANEIA", "CANAS", "CANDIDO MOTA", "CANITAR", "CAPAO BONITO", "CAPELA DO ALTO", "CAPIVARI", "CARAGUATATUBA", "CARAPICUIBA", "CARDOSO", "CASA BRANCA", "CASTILHO", "CATANDUVA", "CATIGUA", "CEDRAL", "CERQUEIRA CESAR", "CERQUILHO", "CESARIO LANGE", "CHARQUEADA", "CHAVANTES", "CLEMENTINA", "COLINA", "COLOMBIA", "CONCHAL", "CONCHAS", "CORDEIROPOLIS", "COSMOPOLIS", "COSMORAMA", "COTIA", "CRAVINHOS", "CRUZEIRO", , "CUBATAO", "CUNHA", "DESCALVADO", "DIADEMA", "DIVINOLANDIA", "DOBRADA", "DOIS CORREGOS", "DRACENA", "DUARTINA", "DUMONT", "ECHAPORA", "ELDORADO", "ELIAS FAUSTO", "ELISIARIO", "EMBAUBA", "EMBU DAS ARTES", "EMBU-GUACU", "ENGENHEIRO COELHO", "ESPIRITO SANTO DO PINHAL", "ESPIRITO SANTO DO TURVO", "ESTRELA D OESTE", "ESTRELA DO NORTE", "EUCLIDES DA CUNHA PAULISTA", "FARTURA", "FERNANDOPOLIS", "FERNAO", "FERRAZ DE VASCONCELOS", "FLORA RICA", "FLOREAL", "FLORIDA PAULISTA", "FLORINEA", "FRANCA", "FRANCISCO MORATO", "FRANCO DA ROCHA", "GALIA", "GARCA", "GENERAL SALGADO", "GETULINA", "GLICERIO", "GUAICARA", "GUAIMBE", "GUAIRA", "GUAPIACU", "GUAPIARA", "GUARA", "GUARACAI", "GUARACI", "GUARANTA", "GUARARAPES", "GUARAREMA", "GUARATINGUETA", "GUAREI", "GUARIBA", "GUARUJA", "GUARULHOS", "GUATAPARA", "HERCULANDIA", "HOLAMBRA", "HORTOLANDIA", "IACANGA", "IACRI", "IARAS", "IBATE", "IBIRA", "IBITINGA", "IBIUNA", "ICEM", "IGARACU DO TIETE", "IGARAPAVA", "IGARATA", "IGUAPE", "ILHABELA", "ILHA COMPRIDA", "ILHA SOLTEIRA", "INDAIATUBA", "INDIANA", "INUBIA PAULISTA", "IPAUSSU", "IPERO", "IPEUNA", "IPIGUA", "IPORANGA", "IPUA", "IRACEMAPOLIS", "IRAPURU", "ITABERA", "ITAI", "ITAJOBI", "ITANHAEM", "ITAPECERICA DA SERRA", "ITAPETININGA", "ITAPEVA", "ITAPEVI", "ITAPIRA", "ITAPIRAPUA PAULISTA", "ITAPOLIS", "ITAPORANGA", "ITAPUI", "ITAPURA", "ITAQUAQUECETUBA", "ITARARE", "ITARIRI", "ITATIBA", "ITATINGA", "ITIRAPINA", "ITIRAPUA", "ITU", "ITUPEVA", "ITUVERAVA", "JABORANDI", "JABOTICABAL", "JACAREI", "JACI", "JACUPIRANGA", "JAGUARIUNA", "JALES", "JANDIRA", "JARDINOPOLIS", "JARINU", "JAU", "JERIQUARA", "JOANOPOLIS", "JOAO RAMALHO", "JOSE BONIFACIO", "JULIO MESQUITA", "JUMIRIM", "JUNDIAI", "JUNQUEIROPOLIS", "JUQUIA", "JUQUITIBA", "LAGOINHA", "LARANJAL PAULISTA", "LAVINIA", "LAVRINHAS", "LEME", "LENCOIS PAULISTA", "LIMEIRA", "LINS", "LORENA", "LOUVEIRA", "LUCELIA", "LUIS ANTONIO", "LUPERCIO", "LUTECIA", "MACATUBA", "MACAUBAL", "MAGDA", "MAIRINQUE", "MAIRIPORA", "MANDURI", "MARABA PAULISTA", "MARACAI", "MARILIA", "MARTINOPOLIS", "MATAO", "MAUA", "MENDONCA", "MERIDIANO", "MIGUELOPOLIS", "MINEIROS DO TIETE", "MIRACATU", "MIRA ESTRELA", "MIRANDOPOLIS", "MIRANTE DO PARANAPANEMA", "MIRASSOL", "MIRASSOLANDIA", "MOCOCA", "MOGI DAS CRUZES", "MOGI GUACU", "MOGI MIRIM", "MOMBUCA", "MONGAGUA", "MONTE ALTO", "MONTE APRAZIVEL", "MONTE AZUL PAULISTA", "MONTEIRO LOBATO", "MONTE MOR", "MORRO AGUDO", "MORUNGABA", "MOTUCA", "NANTES", "NARANDIBA", "NATIVIDADE DA SERRA", "NAZARE PAULISTA", "NEVES PAULISTA", "NHANDEARA", "NIPOA", "NOVA ALIANCA", "NOVA CAMPINA", "NOVA EUROPA", "NOVA GRANADA", "NOVA GUATAPORANGA", "NOVA INDEPENDENCIA", "NOVAIS", "NOVA LUZITANIA", "NOVA ODESSA", "NOVO HORIZONTE", "NUPORANGA", "OCAUCU", "OLIMPIA", "ONDA VERDE", "ORIENTE", "ORINDIUVA", "ORLANDIA", "OSASCO", "OSVALDO CRUZ", "OURINHOS", "OUROESTE", "PACAEMBU", "PALMARES PAULISTA", "PALMEIRA D OESTE", "PALMITAL", "PANORAMA", "PARAGUACU PAULISTA", "PARAIBUNA", "PARANAPANEMA", "PARANAPUA", "PARAPUA", "PARDINHO", "PARIQUERA-ACU", "PATROCINIO PAULISTA", "PAULICEIA", "PAULINIA", "PAULO DE FARIA", "PEDERNEIRAS", "PEDRA BELA", "PEDREGULHO", "PEDREIRA", "PENAPOLIS", "PEREIRA BARRETO", "PEREIRAS", "PERUIBE", "PIACATU",
            "PIEDADE",
            "PILAR DO SUL",
            "PINDAMONHANGABA",
            "PINDORAMA",
            "PINHALZINHO",
            "PIQUETE",
            "PIRACAIA",
            "PIRACICABA",
            "PIRAJU",
            "PIRAJUI",
            "PIRANGI",
            "PIRAPOZINHO",
            "PIRASSUNUNGA",
            "PITANGUEIRAS",
            "PLANALTO",
            "PLATINA",
            "POA",
            "POLONI",
            "POMPEIA",
            "PONGAI",
            "PONTAL",
            "PORANGABA",
            "PORTO FELIZ",
            "PORTO FERREIRA",
            "POTIM",
            "POTIRENDABA",
            "PRADOPOLIS",
            "PRAIA GRANDE",
            "PRESIDENTE BERNARDES",
            "PRESIDENTE EPITACIO",
            "PRESIDENTE PRUDENTE",
            "PRESIDENTE VENCESLAU",
            "PROMISSAO",
            "QUADRA",
            "QUELUZ",
            "QUINTANA",
            "RAFARD",
            "RANCHARIA",
            "REGENTE FEIJO",
            "REGINOPOLIS",
            "REGISTRO",
            "RESTINGA",
            "RIBEIRAO BONITO",
            "RIBEIRAO BRANCO",
            "RIBEIRAO DO SUL",
            "RIBEIRAO PIRES",
            "RIBEIRAO PRETO",
            "RIFAINA",
            "RINCAO",
            "RIO CLARO",
            "RIO DAS PEDRAS",
            "RIO GRANDE DA SERRA",
            "RIOLANDIA",
            "ROSANA",
            "ROSEIRA",
            "SABINO",
            "SALES",
            "SALES OLIVEIRA",
            "SALESOPOLIS",
            "SALTINHO",
            "SALTO",
            "SALTO DE PIRAPORA",
            "SALTO GRANDE",
            "SANDOVALINA",
            "SANTA ADELIA",
            "SANTA ALBERTINA",
            "SANTA BARBARA D OESTE",
            "SANTA BRANCA",
            "SANTA CRUZ DA CONCEICAO",
            "SANTA CRUZ DA ESPERANCA",
            "SANTA CRUZ DAS PALMEIRAS",
            "SANTA CRUZ DO RIO PARDO",
            "SANTA FE DO SUL",
            "SANTA GERTRUDES",
            "SANTA ISABEL",
            "SANTA MARIA DA SERRA",
            "SANTA MERCEDES",
            "SANTANA DA PONTE PENSA",
            "SANTANA DE PARNAIBA",
            "SANTA RITA DO PASSA QUATRO",
            "SANTA ROSA DO VITERBO",
            "SANTA SALETE",
            "SANTO ANASTACIO",
            "SANTO ANDRE",
            "SANTO ANTONIO DA ALEGRIA",
            "SANTO ANTONIO DE POSSE",
            "SANTO ANTONIO DO ARACANGUA",
            "SANTO ANTONIO DO JARDIM",
            "SANTO ANTONIO DO PINHAL",
            "SANTO EXPEDITO",
            "SANTOPOLIS DO AGUAPEI",
            "SANTOS",
            "SAO BENTO DO SAPUCAI",
            "SAO BERNARDO DO CAMPO",
            "SAO CAETANO DO SUL",
            "SAO CARLOS",
            "SAO JOAO DA BOA VISTA",
            "SAO JOAQUIM DA BARRA",
            "SAO JOSE DO BARREIRO",
            "SAO JOSE DO RIO PARDO",
            "SAO JOSE DO RIO PRETO",
            "SAO JOSE DOS CAMPOS",
            "SAO LOURENCO DA SERRA",
            "SAO LUIS DO PARAITINGA",
            "SAO MANUEL",
            "SAO MIGUEL ARCANJO",
            "SAO PAULO",
            "SAO PEDRO",
            "SAO PEDRO DO TURVO",
            "SAO ROQUE",
            "SAO SEBASTIAO",
            "SAO SEBASTIAO DA GRAMA",
            "SAO SIMAO",
            "SAO VICENTE",
            "SERRA AZUL",
            "SERRANA",
            "SERRA NEGRA",
            "SERTAOZINHO",
            "SETE BARRAS",
            "SEVERINIA",
            "SILVEIRAS",
            "SOCORRO",
            "SOROCABA",
            "SUD MENNUCCI",
            "SUMARE",
            "SUZANAPOLIS",
            "SUZANO",
            "TABAPUA",
            "TABATINGA",
            "TABOAO DA SERRA",
            "TACIBA",
            "TAGUAI",
            "TAIACU",
            "TAIUVA",
            "TAMBAU",
            "TANABI",
            "TAPIRAI",
            "TAQUARITINGA",
            "TAQUARITUBA",
            "TAQUARIVAI",
            "TARABAI",
            "TARUMA",
            "TATUI",
            "TAUBATE",
            "TEODORO SAMPAIO",
            "TERRA ROXA",
            "TIETE",
            "TORRINHA",
            "TRABIJU",
            "TREMEMBE",
            "TRES FRONTEIRAS",
            "TUPA",
            "TUPI PAULISTA",
            "TURMALINA",
            "UBARANA",
            "UBATUBA",
            "UCHOA",
            "URANIA",
            "URUPES",
            "VALENTIM GENTIL",
            "VALINHOS",
            "VALPARAISO",
            "VARGEM",
            "VARGEM GRANDE DO SUL",
            "VARGEM GRANDE PAULISTA",
            "VARZEA PAULISTA",
            "VINHEDO",
            "VIRADOURO",
            "VISTA ALEGRE DO ALTO",
            "VITORIA BRASIL",
            "VOTORANTIM",
            "VOTUPORANGA",
            "ZACARIAS"
        ],
        datasets: [{
            label: 'Quantidade de acidentes',
            data: [
                2,
                1,
                3,
                6,
                3,
                3,
                4,
                1,
                3,
                1,
                1,
                28,
                1,
                3,
                20,
                2,
                8,
                5,
                2,
                8,
                2,
                14,
                19,
                7,
                5,
                37,
                22,
                1,
                9,
                18,
                15,
                27,
                2,
                4,
                12,
                2,
                3,
                3,
                10,
                21,
                4,
                39,
                6,
                8,
                45,
                16,
                1,
                2,
                25,
                18,
                9,
                2,
                1,
                5,
                6,
                1,
                4,
                13,
                26,
                3,
                2,
                2,
                4,
                2,
                1,
                11,
                18,
                11,
                2,
                4,
                14,
                2,
                9,
                18,
                3,
                1,
                155,
                10,
                8,
                3,
                3,
                5,
                6,
                1,
                16,
                5,
                6,
                10,
                23,
                2,
                8,
                4,
                21,
                5,
                2,
                7,
                5,
                4,
                4,
                2,
                3,
                6,
                1,
                2,
                6,
                2,
                7,
                5,
                34,
                7,
                10,
                26,
                11,
                4,
                35,
                3,
                4,
                4,
                5,
                2,
                5,
                1,
                1,
                6,
                2,
                2,
                20,
                9,
                3,
                6,
                1,
                1,
                1,
                3,
                4,
                15,
                1,
                6,
                1,
                2,
                2,
                2,
                47,
                5,
                20,
                2,
                5,
                5,
                4,
                3,
                3,
                3,
                3,
                4,
                2,
                3,
                2,
                2,
                1,
                6,
                12,
                24,
                1,
                2,
                30,
                116,
                2,
                4,
                1,
                26,
                1,
                2,
                2,
                6,
                6,
                5,
                23,
                6,
                2,
                5,
                2,
                16,
                4,
                4,
                8,
                36,
                2,
                2,
                2,
                4,
                1,
                3,
                2,
                5,
                5,
                2,
                8,
                6,
                4,
                22,
                24,
                32,
                16,
                13,
                18,
                1,
                8,
                7,
                3,
                2,
                41,
                6,
                4,
                16,
                7,
                7,
                2,
                44,
                6,
                7,
                2,
                15,
                25,
                1,
                3,
                5,
                12,
                2,
                9,
                7,
                22,
                1,
                3,
                2,
                10,
                1,
                4,
                96,
                4,
                5,
                11,
                2,
                2,
                1,
                4,
                16,
                7,
                39,
                8,
                14,
                7,
                1,
                2,
                2,
                3,
                3,
                1,
                2,
                11,
                17,
                1,
                1,
                6,
                39,
                7,
                7,
                32,
                2,
                3,
                2,
                4,
                17,
                1,
                6,
                15,
                8,
                3,
                12,
                66,
                25,
                17,
                2,
                6,
                10,
                11,
                5,
                1,
                10,
                8,
                3,
                4,
                1,
                1,
                1,
                7,
                5,
                1,
                1,
                1,
                1,
                1,
                3,
                1,
                1,
                1,
                1,
                6,
                6,
                2,
                4,
                19,
                3,
                5,
                2,
                9,
                58,
                5,
                12,
                2,
                3,
                6,
                3,
                8,
                3,
                2,
                2,
                3,
                1,
                11,
                6,
                8,
                4,
                1,
                9,
                1,
                8,
                1,
                1,
                4,
                6,
                3,
                4,
                14,
                1,
                11,
                9,
                31,
                2,
                4,
                1,
                4,
                61,
                4,
                3,
                2,
                4,
                9,
                11,
                1,
                1,
                4,
                1,
                1,
                1,
                7,
                1,
                16,
                11,
                3,
                2,
                1,
                56,
                1,
                8,
                29,
                5,
                7,
                2,
                3,
                3,
                3,
                12,
                2,
                5,
                10,
                3,
                1,
                2,
                1,
                34,
                92,
                1,
                3,
                25,
                6,
                1,
                2,
                1,
                2,
                2,
                2,
                1,
                3,
                1,
                11,
                13,
                6,
                1,
                4,
                2,
                22,
                1,
                8,
                1,
                2,
                10,
                4,
                4,
                17,
                3,
                1,
                1,
                11,
                7,
                2,
                2,
                1,
                45,
                2,
                3,
                2,
                2,
                1,
                1,
                2,
                54,
                6,
                89,
                5,
                29,
                14,
                10,
                1,
                7,
                72,
                81,
                3,
                2,
                17,
                1,
                883,
                7,
                2,
                29,
                20,
                2,
                4,
                30,
                2,
                5,
                3,
                25,
                1,
                3,
                1,
                10,
                89,
                1,
                32,
                1,
                27,
                3,
                3, 15, 3, 3, 1, 2, 2, 5, 4, 9, 3, 1, 2, 7, 29, 38, 6, 1, 11, 1, 1, 4, 2, 12, 3, 1, 3, 15, 9, 1, 9, 3, 11, 3, 5, 7, 4, 6, 11, 2, 3, 1, 14, 19, 3

            ],
            backgroundColor: '#FFCA28',
            borderColor: '#FFCA28',
            borderWidth: 1
        }]
    },
    options: {
        plugins: {
            datalabels: {
                display: false
            },
            deferred: {
                xOffset: 50, // defer until 150px of the canvas width are inside the viewport
                yOffset: '50%', // defer until 50% of the canvas height are inside the viewport
                delay: 300 // delay of 500 ms after the canvas is considered inside the viewport
            }

        }
    }
});